# -*- coding: utf-8 -*-
"""CodeAlpha_FAQ_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vUvgfywiz_0lj7F2XDYf6tIYpte1_6U
"""

print("Hello! I am building my CodeAlpha FAQ Chatbot.")

import sklearn
print("scikit-learn is working!")
print(sklearn.__version__)

faqs = [
    {
        "question": "What is Python?",
        "answer": "Python is a high-level programming language widely used in artificial intelligence, machine learning, data science and web development."
    },
    {
        "question": "What is artificial intelligence?",
        "answer": "Artificial Intelligence is a field of computer science that enables machines to perform tasks that normally require human intelligence."
    },
    {
        "question": "What is machine learning?",
        "answer": "Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions."
    },
    {
        "question": "What is deep learning?",
        "answer": "Deep Learning is a type of machine learning that uses neural networks with multiple layers to learn complex patterns."
    },
    {
        "question": "What is NLP?",
        "answer": "NLP stands for Natural Language Processing. It allows computers to understand, process and work with human language."
    },
    {
        "question": "What is computer vision?",
        "answer": "Computer Vision is a field of AI that enables computers to understand and analyze images and videos."
    },
    {
        "question": "What programming language is commonly used for AI?",
        "answer": "Python is one of the most commonly used programming languages for artificial intelligence and machine learning."
    },
    {
        "question": "What is an AI internship?",
        "answer": "An AI internship provides practical experience in areas such as artificial intelligence, machine learning, data science and related technologies."
    }
]

print(get_answer("Tell me about machine learning"))

print(len(faqs))

questions = [item["question"] for item in faqs]

print(questions)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

faq_vectors = vectorizer.fit_transform(questions)

print(faq_vectors.shape)

user_question = "What is Machine Learning?"

user_vector = vectorizer.transform([user_question])

print(user_vector.shape)

from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(user_vector, faq_vectors)

print(similarities)

user_question = "Can you explain machine learning?"

user_vector = vectorizer.transform([user_question])

print(user_vector.shape)

best_match_index = similarities.argmax()

print(best_match_index)

print(faqs[best_match_index]["question"])

answer = faqs[best_match_index]["answer"]

print(answer)

def get_answer(user_question):
    user_vector = vectorizer.transform([user_question])
    similarities = cosine_similarity(user_vector, faq_vectors)

    best_match_index = similarities.argmax()
    best_score = similarities[0][best_match_index]

    if best_score < 0.25:
        return "Sorry, I don't know the answer to that question."

    return answers[best_match_index]

print(get_answer("Tell me about machine learning"))

answers = [
    "Python is a popular programming language widely used in AI, machine learning, web development, and data science.",
    "Artificial Intelligence (AI) is the field of creating computer systems that can perform tasks that normally require human intelligence.",
    "Machine Learning (ML) is a subset of AI where computers learn patterns from data and use those patterns to make predictions or decisions.",
    "Deep Learning is a type of machine learning that uses neural networks with multiple layers to learn complex patterns from data.",
    "Natural Language Processing (NLP) is a branch of AI that enables computers to understand, process, and generate human language.",
    "Computer Vision is a field of AI that enables computers to understand and analyze images and videos.",
    "Python is one of the most commonly used programming languages for AI because of its simple syntax and powerful libraries.",
    "An AI internship provides practical experience in artificial intelligence, machine learning, data science, or related technologies."
]

print(get_answer("What does NLP mean?"))

while True:
    user_question = input("You: ")

    if user_question.lower() == "exit":
        print("Bot: Goodbye!")
        break

    answer = get_answer(user_question)

    print("Bot:", answer)

import gradio as gr
print("Gradio is working!")
print(gr.__version__)

import gradio as gr

demo = gr.Interface(
    fn=get_answer,
    inputs=gr.Textbox(
        label="💬 Ask your question",
        placeholder="Type your question here..."
    ),
    outputs=gr.Textbox(
        label="🤖 Chatbot Answer"
    ),
    title="🤖 AI FAQ Chatbot",
    description="An intelligent FAQ chatbot powered by Python, TF-IDF and cosine similarity.",
    theme=gr.themes.Soft()
)

demo.launch()

print(questions)